module.exports = {
  'EUR': '€',
  'GBP': '£',
  'CHF': 'CHF',
  'USD': 'US $',
  'AUD': 'AU $',
  'CAD': 'CA $',
  'SEK': 'kr',
  'HKD': 'HK$',
  'HRK': 'kn',
  'HUF': 'HUF',
  'DKK': 'kr',
  'PLN': 'zł',
  'NOK': 'kr',
  'BGN': 'лв',
  'MXN': 'MEX $',
  'ISK': 'kr',
  'CZK': 'Kč',
  'RON': 'RON',
  'NZD': 'NZ $'
}
